### ISSUE TITLE
Problems add a dependency after upgrade parent

### ISSUE THREAD

**Issue by ruben-garciapariente** [openrewrite/rewrite-maven-plugin#233]
Hi

When upgrading the parent, if I subsequently add a new dependency that is not handled by the parent, the version attribute is added unnecessarily.

Example in https://github.com/ruben-garciapariente/test-openwrite/tree/957ce2aa91db9b8c61b543ec34057c7f7ef68609

Recipe
```yaml
  - org.openrewrite.maven.UpgradeParentVersion:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-parent
      newVersion: 2.3.X

  - org.openrewrite.maven.RemoveDependency:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-web

  - org.openrewrite.maven.AddDependency:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-webflux
      version: 2.3.X
      onlyIfUsing: org.springframework.boot.*
```

Maven pom parent
```xml
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.22.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
```

In this result you could see the attribute version
```
diff --git a/pom.xml b/pom.xml
index 2c5c68c..01d3585 100644
--- a/pom.xml
+++ b/pom.xml
@@ -14,7 +14,7 @@ org.openrewrite.maven.AddDependency, org.openrewrite.maven.RemoveDependency, org.openrewrite.maven.UpgradeParentVersion
 	<parent>
 		<groupId>org.springframework.boot</groupId>
 		<artifactId>spring-boot-starter-parent</artifactId>
-		<version>1.5.22.RELEASE</version>
+		<version>2.3.12.RELEASE</version>
 		<relativePath/> <!-- lookup parent from repository -->
 	</parent>
 
@@ -26,10 +26,11 @@
 		<dependency>
 			<groupId>org.springframework.boot</groupId>
 			<artifactId>spring-boot-starter-actuator</artifactId>
-		</dependency>
-		<dependency>
-			<groupId>org.springframework.boot</groupId>
-			<artifactId>spring-boot-starter-web</artifactId>
+		</dependency>
+		<dependency>
+			<groupId>org.springframework.boot</groupId>
+			<artifactId>spring-boot-starter-webflux</artifactId>
+			<version>2.3.12.RELEASE</version>
 		</dependency>
```

I am using rewrite-maven-plugin 4.14.1

If we update a pom from a more recent version
```xml
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.9.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
```

Then, there is no problem
```
diff --git a/pom.xml b/pom.xml
index 75c69d7..dc5ef9f 100644
--- a/pom.xml
+++ b/pom.xml
@@ -14,7 +14,7 @@ org.openrewrite.maven.AddDependency, org.openrewrite.maven.RemoveDependency, org.openrewrite.maven.UpgradeParentVersion
 	<parent>
 		<groupId>org.springframework.boot</groupId>
 		<artifactId>spring-boot-starter-parent</artifactId>
-		<version>2.3.9.RELEASE</version>
+		<version>2.3.12.RELEASE</version>
 		<relativePath/> <!-- lookup parent from repository -->
 	</parent>
 
@@ -26,10 +26,10 @@
 		<dependency>
 			<groupId>org.springframework.boot</groupId>
 			<artifactId>spring-boot-starter-actuator</artifactId>
-		</dependency>
-		<dependency>
-			<groupId>org.springframework.boot</groupId>
-			<artifactId>spring-boot-starter-web</artifactId>
+		</dependency>
+		<dependency>
+			<groupId>org.springframework.boot</groupId>
+			<artifactId>spring-boot-starter-webflux</artifactId>
 		</dependency>
 
 		<!-- Test -->
```

Thank you very much for the excellent support you provide

Thanks & regards
