### ISSUE TITLE
Duplicated recipes in logs

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-maven-plugin#326]
While running open rewrite in my module, I noticed that the log of the same recipe is printed more than once. Does this mean that it transformed two instances? If so, maybe it should be printed only once? 

See : 

```
[WARNING] Changes have been made to Hello.java by:
[WARNING]     org.openrewrite.java.logging.ParameterizedLogging
[WARNING]     org.openrewrite.java.cleanup.FinalizeLocalVariables
[WARNING]     org.openrewrite.java.logging.ParameterizedLogging
```

**Comment by tkvangorder** [comment]
This is likely because there are two different instances of the Parameterized logging (with different configurations)

**Comment by yeikel** [comment]
The only two logging related recipes that I have are : 


```
➜  cat pom.xml | grep "org.openrewrite.java.logging"
                        <recipe>org.openrewrite.java.logging.slf4j.ParameterizedLogging</recipe>
                        <recipe>org.openrewrite.java.logging.PrintStackTraceToLogError</recipe>

```

**Comment by yeikel** [comment]
This is possibly related to https://github.com/openrewrite/rewrite-logging-frameworks/issues/60#issuecomment-1093189052

**Comment by tkvangorder** [comment]
thanks, I will take a closer look

**Comment by pway99** [comment]
For a bit more context:
The duplicate log messages are caused by `org.openrewrite.java.logging.slf4j.ParameterizedLogging` having one `org.openrewrite.java.logging.ParameterizedLogging` recipe configuration for each log level.  `Hello.java` most likely has at least two logging statements with different log levels.

```YAML
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.logging.slf4j.ParameterizedLogging
displayName: Parameterize SLF4J logging statements
description: SLF4J supports parameterized logging, which can significantly boost logging performance for disabled logging statements.
tags:
  - logging
  - slf4j
  - RSPEC-2629
recipeList:
  - org.openrewrite.java.logging.ParameterizedLogging:
      methodPattern: org.slf4j.Logger trace(..)
  - org.openrewrite.java.logging.ParameterizedLogging:
      methodPattern: org.slf4j.Logger debug(..)
  - org.openrewrite.java.logging.ParameterizedLogging:
      methodPattern: org.slf4j.Logger info(..)
  - org.openrewrite.java.logging.ParameterizedLogging:
      methodPattern: org.slf4j.Logger warn(..)
  - org.openrewrite.java.logging.ParameterizedLogging:
      methodPattern: org.slf4j.Logger error(..)
```
