### ISSUE TITLE
rewriteRun adds a `Maven` Xml.Document with a different sourcePath than the current MavenProject

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-maven-plugin#351]
Maven builds multi-module projects in project reactor order.
As each project is built the `mavenProject` is equivalent to `mavenSession.getCurrentProject`.

The `Xml.Document` returned from the `MavenParserBuilder` typically does not match the current maven project pom. AFAICT the XML document that is returned always has the same source path.

```yaml
root:
  module1:
    - pom1.xml # hypothetical example of what is returned from MavenParserBuilder.
  module2:
    - pom2.xml # parser builder will return pom1.xml, so the resource parse will pick up pom2.xml without markers.
```
