### ISSUE TITLE
Passing -DactiveRecipe seems to have no effect

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite-maven-plugin#368]
I'm trying to build a process to add plug-ins including OpenRewrite to POM files but when I try to run the following command no activeRecipes are detected:

```shell
mvn org.openrewrite.maven:rewrite-maven-plugin:run -DactiveRecipe=com.difrango.AddSortPom
```

And the output is:

```shell
[INFO] --- rewrite-maven-plugin:4.24.0:run (default-cli) @ ztester ---
[INFO] Using active recipe(s) []
[INFO] Using active styles(s) []
```

Here's the `rewrite.yml` file:

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.difrango.AddSortPom
displayName: Add Maven SortPom plugin
recipeList:
    - org.openrewrite.maven.AddPlugin:
          groupId: com.github.ekryd.sortpom
          artifactId: sortpom-maven-plugin
          version: 3.0.1
          configuration: <configuration><predefinedSortOrder>custom_1</predefinedSortOrder><lineSeparator>\n</lineSeparator><encoding>${project.build.sourceEncoding}</encoding><nrOfIndentSpace>-1</nrOfIndentSpace><sortProperties>true</sortProperties><sortDependencies>scope,groupId,artifactId</sortDependencies></configuration>
          executions: <executions><execution><goals><goal>sort</goal></goals><phase>verify</phase></execution></executions>
```

and the POM file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.7</version>
    </parent>

    <groupId>com.difrango.examples</groupId>
    <artifactId>ztester</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <name>ztester</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>17</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
```
