### ISSUE TITLE
AddPlugin Reports: Illegal character in path at index 72

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite-maven-plugin#399]
I'm trying to use `org.openrewrite.maven.AddPlugin` and I'm getting the following failure:

```
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.27.0:run failed: Illegal character in path at index 72: file:///Users/a683481/.m2/repository/org/apache/maven/maven-plugin-api/${project.prerequisites.maven}/maven-plugin-api-${project.prerequisites.maven}.pom
```

Here's the rewrite.yml:

```
---
type: specs.openrewrite.org/v1beta/recipe
name: com.difrango.AddSortPom
displayName: Add in the sortpom (https://github.com/Ekryd/sortpom) plugin.
recipeList:
  - org.openrewrite.maven.AddPlugin:
      groupId: com.github.ekryd.sortpom
      artifactId: sortpom-maven-plugin
      version: latest.release
      configuration: <configuration> <predefinedSortOrder>custom_1</predefinedSortOrder> <lineSeparator>\n</lineSeparator> <encoding>${project.build.sourceEncoding}</encoding> <nrOfIndentSpace>4</nrOfIndentSpace> <sortProperties>true</sortProperties> <sortDependencies>scope,groupId,artifactId</sortDependencies> </configuration>
      executions: <executions> <execution> <goals> <goal>sort</goal> </goals> <phase>verify</phase> </execution> </executions>
```
