### ISSUE TITLE
Do not print markers like <!--~~(No version provided)~~>-->

### ISSUE THREAD

**Issue by ge0ffrey** [openrewrite/rewrite-maven-plugin#522]
Or at least make the print markers optional and turn them off by default.

To reproduce:

Use maven plugin 4.41.1 (= latest release) with a recipe like this:

```
  - org.openrewrite.maven.ChangeDependencyGroupIdAndArtifactId:
      oldGroupId: org.foo
      oldArtifactId: foo
      newGroupId: org.bar
      newArtifactId: bar
```

on a pom file that has the an org.foo:foo dependency without the version, but does import a bom file which defines the version of org.foo:foo.

Notice how afterwards, the output contains `<!--~~(No version provided)~~>-->` in the dependency declaration of org.bar:bar, even if there's a bom file which defines the version of org.bar:bar.

Slack conversation: https://rewriteoss.slack.com/archives/C01A843MWG5/p1678112429218709
