### ISSUE TITLE
Running a recipe that wraps recipes from other Maven artifacts with parameters from the command line

### ISSUE THREAD

**Issue by thombergs** [openrewrite/rewrite-maven-plugin#821]
Hey! Great tool with great impact (that I'm currently trying to channel for my work)!

I'm trying to figure out how to run a recipe with parameters from the command line using the Maven plugin. I followed [this guide](https://docs.openrewrite.org/running-recipes/running-rewrite-on-a-maven-project-without-modifying-the-build) but hit a wall. 

## This works
I understand that I can create a `rewrite.yml` file that "wraps" any existing recipes in its `recipeList`. Everything works fine as long as the recipes mentioned in that list are in the plugin's classpath. I.e. this works fine:

```yaml
# rewrite.yml
---
type: specs.openrewrite.org/v1beta/recipe
name: paver.maven.AddGuavaDependency
displayName: Add Maven dependency example
recipeList:
  - org.openrewrite.maven.AddDependency:
      groupId: com.google.guava
      artifactId: guava
      version: 33.2.1
      versionPattern: '-jre'
      scope: runtime
      onlyIfUsing: org.junit.jupiter.api.*
      type: jar
      classifier: test
      familyPattern: com.fasterxml.jackson*
      acceptTransitive: true
```
```
mvn org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.activeRecipes=paver.maven.AddGuavaDependency
```
```
...
[WARNING] Changes have been made to rewrite-test/pom.xml by:
[WARNING]     paver.maven.AddGuavaDependency
[WARNING]         org.openrewrite.maven.AddDependency: ...
```

All good in this case, the recipe has been applied successfully :).

## This doesn't work (wrapping a recipe from another artifact)
As soon as the `recipeList` contains a recipe that is not in the plugin's classpath, it stops working. I.e. when I try to run the `gradle.AddDependency` recipe instead (yes, for this case I have a `pom.xml` and a `build.gradle` in the same project, it's just a test :) ):

```yaml
# rewrite.yml
---
type: specs.openrewrite.org/v1beta/recipe
name: paver.gradle.AddGuavaDependency
displayName: Add Gradle dependency example
recipeList:
  - org.openrewrite.gradle.AddDependency:
      groupId: com.google.guava
      artifactId: guava
      version: 33.2.1
      versionPattern: '-jre'
      configuration: implementation
      onlyIfUsing: org.junit.jupiter.api.*
      classifier: test
      extension: jar
      familyPattern: com.fasterxml.jackson*
      acceptTransitive: true
```
```
mvn org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.activeRecipes=paver.gradle.AddGuavaDependency
```

I get this error:

```
[ERROR] Recipe validation error in org.openrewrite.gradle.AddDependency: Recipe class org.openrewrite.gradle.AddDependency cannot be found
```
This is understandable because I don't expect the Maven plugin to have the Gradle recipes in its belly.

## This also doesn't work (providing the artifact coordinates)
So, I thought I can fix this by providing the Maven coordinates to the artifact that contains the recipe class:

```
mvn org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.activeRecipes=paver.gradle.AddGuavaDependency \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite:rewrite-gradle:8.30.0
```

And, indeed, this doesn't fail with an error, it outputs this:
```
[INFO] Using active recipe(s) [paver.gradle.AddGuavaDependency]
[INFO] Using active styles(s) []
[INFO] Validating active recipes...
[INFO] Project [rewrite-test] Resolving Poms...
[INFO] Project [rewrite-test] Parsing source files
[INFO] Running recipe(s)...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

... but it also doesn't apply the `paver.gradle.AddGuavaDependency` recipe (I assume because it looks for this recipe in the artifact, but doesn't find it ... because this recipe is in my `rewrite.yml` file!). 

## Question
So, my question is: how can I use the Maven Plugin to apply a recipe from my own `rewrite.yml` file that contains one or more recipes in its `recipeList` which can be found in other (potentially multiple) Maven artifacts? It feels like the Plugin should be able to do this :). If it's a missing feature, I'd be happy to try contributing.

 I've been using the latest version of the Maven plugin (5.36.0).
